# Project Name
TARGET = Tymbal

# Sources
CPP_SOURCES = Tymbal.cpp \

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Shared DSP header at repo root
C_INCLUDES += -I..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
